package com.animalguard.mqtt;

public enum AckHandlingOutcome {
    APPLIED,
    IDEMPOTENT,
    ADVANCED_IGNORED,
    UNKNOWN_COMMAND,
    TOPIC_PAYLOAD_DEVICE_MISMATCH,
    DATABASE_DEVICE_MISMATCH,
    ORDER_VIOLATION,
    TERMINAL_CONFLICT,
    OPTIMISTIC_LOCK_ABORTED
}
