CREATE TABLE detection_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(100) NOT NULL,
    camera_id VARCHAR(100) NOT NULL,
    captured_at TIMESTAMP WITH TIME ZONE NOT NULL,
    image_width INTEGER NOT NULL,
    image_height INTEGER NOT NULL,
    detector_version VARCHAR(128) NOT NULL,
    classifier_version VARCHAR(128),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_detection_events_event_id UNIQUE (event_id)
);

CREATE TABLE animal_detections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    detection_id VARCHAR(64) NOT NULL,
    track_id BIGINT,
    class_code VARCHAR(64) NOT NULL,
    detection_confidence DOUBLE PRECISION NOT NULL,
    classification_confidence DOUBLE PRECISION,
    bbox_x INTEGER NOT NULL,
    bbox_y INTEGER NOT NULL,
    bbox_width INTEGER NOT NULL,
    bbox_height INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_animal_detections_event_detection UNIQUE (event_id, detection_id),
    CONSTRAINT fk_animal_detections_event FOREIGN KEY (event_id) REFERENCES detection_events (id)
);

CREATE TABLE risk_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    risk_score INTEGER NOT NULL,
    risk_level VARCHAR(10) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_risk_decisions_event_id UNIQUE (event_id),
    CONSTRAINT fk_risk_decisions_event FOREIGN KEY (event_id) REFERENCES detection_events (id)
);

CREATE TABLE device_commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_id VARCHAR(100) NOT NULL,
    event_id BIGINT NOT NULL,
    device_id VARCHAR(100) NOT NULL,
    command_type VARCHAR(100) NOT NULL,
    duration_ms INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_device_commands_command_id UNIQUE (command_id),
    CONSTRAINT fk_device_commands_event FOREIGN KEY (event_id) REFERENCES detection_events (id)
);

CREATE TABLE device_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id VARCHAR(100) NOT NULL,
    connected BOOLEAN NOT NULL,
    last_seen TIMESTAMP WITH TIME ZONE,
    temperature DOUBLE PRECISION
);
