CREATE TABLE animal_observation_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    camera_id VARCHAR(100) NOT NULL,
    presence_state VARCHAR(20) NOT NULL,
    first_detected_at TIMESTAMP WITH TIME ZONE,
    last_detected_at TIMESTAMP WITH TIME ZONE,
    absence_started_at TIMESTAMP WITH TIME ZONE,
    last_processed_captured_at TIMESTAMP WITH TIME ZONE NOT NULL,
    sound_alert_command_id VARCHAR(100),
    deterrent_full_command_id VARCHAR(100),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_animal_observation_states_camera_id UNIQUE (camera_id)
);
